apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
    - name: myapp
      image: codebill/myapp:v1.0.7
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: cache-volume
          mountPath: /app/log
  volumes:
    - name: cache-volume
      emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
    - name: myapp
      port: 3000
