apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      parallelism: 2 # 并发数为
      completions: 4 # 完成任务数量为4
      containers:
        - name: pi
          image: resouer/ubuntu-bc
          command:
            - 'sh'
            - '-c'
            - "echo 'scale=10000;4*a(1)' | bc -l"
      restartPolicy: Never
  backoffLimit: 4
